//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractOSMMapProd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtractOSMMapProd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale is too high, please zoom to a smaller area and try again.
        /// </summary>
        internal static string BigScale {
            get {
                return ResourceManager.GetString("BigScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;&lt;br&gt;Best Regards, &lt;br&gt; D.E.R.A Team &lt;br&gt;.
        /// </summary>
        internal static string EmailGreetingsEn {
            get {
                return ResourceManager.GetString("EmailGreetingsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;&lt;br&gt;Cordialement, &lt;br&gt; L&apos;équipe D.E.R.A &lt;br&gt;.
        /// </summary>
        internal static string EmailGreetingsFr {
            get {
                return ResourceManager.GetString("EmailGreetingsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.E.R.A report of location: .
        /// </summary>
        internal static string EmailSubjectEn {
            get {
                return ResourceManager.GetString("EmailSubjectEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport D.E.R.A de localisation: .
        /// </summary>
        internal static string EmailSubjectFr {
            get {
                return ResourceManager.GetString("EmailSubjectFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild to retrive data.
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
    }
}
